### ISSUE TITLE
Problems with horizontal scrolling

### ISSUE THREAD

**Issue by dead** [tarun-dugar/easy-scroll#2]
First of all thanks for your work on this great library! 😄

I'm having some problems with horizontal scrolling...
1) When I use easyScroll (to right) with a amount of i.e 200px it doesn't move the scroll 200px exactly.
2) When I use easyScroll with the direction to left the scroll simply goes to zero.

[Example](https://codesandbox.io/s/2w39jx5qjp)

I fixed the problem 1 by ensuring that when the animation is finished it will scroll to the amount requested.
The second problem I fixed by changing the [`totalScroll - scrollAmt - initialScrollPosition`](https://github.com/tarun-dugar/easy-scroll/blob/master/src/index.js#L112) to `initialScrollPosition - scrollAmt`

I was also having a problem with this line [`totalScroll = scrollableDomEle[scrollLengthProp] - scrollableDomEle[elementLengthProp];`](https://github.com/tarun-dugar/easy-scroll/blob/master/src/index.js#L49) It would't let me scroll to left in some cases.

I didn't submit a pull-request because I don't know if those changes can break the scrolling in other cases.

**Comment by tarun-dugar** [comment]
@dead thanks for reporting these issues. I'll have a look! 😄

**Comment by phao5814** [comment]
@dead Btw to solve your issue with the left scroll, you can simply keep the scroll direction as "right" and set the scollAmount to a negative value and it will scroll to the left with no issues.

**Comment by tarun-dugar** [comment]
@dead @phao5814 this is fixed in 0.6.0.
