### ISSUE TITLE
Error with Horizontal Scrolling

### ISSUE THREAD

**Issue by vamshikenche** [tarun-dugar/easy-scroll#4]
easyScroll({
        'scrollableDomEle': document.querySelector('.primaryMainCon'),
        'direction': 'right',
        'duration': 3000,
        'easingPreset': 'easeInQuad',
        'scrollAmount': 1000
      });
Error Message in Chrome: 
Object(...) is not a function
Error Message in Safari: 
Object is not a function. (In 'Object(easy_scroll__WEBPACK_IMPORTED_MODULE_4__["easyScroll"])', 'Object' is an instance of Object)

**Comment by tarun-dugar** [comment]
@vamshikenche how are you importing it?
