### ISSUE TITLE
No animation effect and not exactly

### ISSUE THREAD

**Issue by moonlitusun** [tarun-dugar/easy-scroll#5]
It don't have animation effect when `direction`  is *top*, 
and `scrollAmount`  is not exactly
[DEMO](https://codesandbox.io/s/q83nw71vjw)

**Comment by tarun-dugar** [comment]
@moonlitusun thanks for submitting the bug, will fix it in 2-3 days 👍

**Comment by tarun-dugar** [comment]
@moonlitusun fixed. Upgrade to 0.6.0.
