### ISSUE TITLE
SameSite cookie warning in Chrome

### ISSUE THREAD

**Issue by dylankershaw** [tarun-dugar/easy-scroll#6]
Adding this line to my html:
`<script async defer src="https://unpkg.com/easy-scroll"></script>`

Triggers this warning in Chrome 77:
> A cookie associated with a cross-site resource at http://unpkg.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by tarun-dugar** [comment]
@dylankershaw check this: https://stackoverflow.com/questions/58270663/samesite-warning-chrome-77
